from flask import Flask, request, jsonify
from flask_cors import CORS
from model.recommender import HybridCareerRecommender
from dotenv import load_dotenv
import os
import requests

load_dotenv()

app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "http://localhost:5173"}})

recommender = HybridCareerRecommender("data/careers.csv")


@app.route("/")
def home():
    return jsonify({"message": "SkillSakhi backend is running"})


@app.route("/health")
def health():
    return jsonify({"status": "ok"})


@app.route("/recommend", methods=["POST"])
def recommend():
    data = request.get_json()

    if not data:
        return jsonify({"error": "No input data"}), 400

    try:
        result = recommender.recommend(data, top_n=5)

        return jsonify({
            "user_profile": data,
            "predicted_category": result.get("predicted_category", "N/A"),
            "recommended_careers": result.get("recommended_careers", [])
        })

    except Exception as e:
        print("Recommend error:", e)
        return jsonify({
            "error": "Recommendation failed",
            "details": str(e),
            "recommended_careers": []
        }), 500

@app.route("/generate-resume", methods=["POST"])
def generate_resume():
    data = request.get_json() or {}

    user_profile = data.get("user_profile", {})
    career = data.get("career", {})
    template = data.get("template", "ats")

    name = user_profile.get("name", "Your Name")
    email = user_profile.get("email", "your.email@example.com")
    phone = user_profile.get("phone", "Your Phone Number")
    location = user_profile.get("location", "Your Location")

    education = user_profile.get("education", "Your Education")
    skills_text = user_profile.get("skills", "")
    interests = user_profile.get("interests", "N/A")
    career_stage = user_profile.get("career_stage", "N/A")
    preferred_work_mode = user_profile.get("preferred_work_mode", "Flexible")

    career_name = career.get("career_name", "Recommended Career Role")
    category = career.get("category", "Career Field")

    matched = career.get("matched_skills", [])
    missing = career.get("missing_skills", [])
    required = career.get("required_skills", [])

    if isinstance(skills_text, str):
        user_skills = [s.strip() for s in skills_text.split(",") if s.strip()]
    else:
        user_skills = skills_text or []

    core_skills = matched if matched else user_skills
    learning_skills = missing if missing else required[:3]

    note = """
NOTE:
This is a sample resume generated by SkillSakhi. Please edit and customize it before using.
Add your college/university name, real projects, internship experience, certifications, and correct contact details.
"""

    if template == "fresher":
        resume = f"""
{name}
{email} | {phone} | {location}

{note}

CAREER OBJECTIVE
Motivated and detail-oriented candidate seeking an entry-level opportunity as a {career_name}.
Interested in applying skills such as {", ".join(core_skills[:5]) if core_skills else "basic professional skills"} and growing through practical learning.

EDUCATION
{education}
Add your college/university name here
Add passing year here

SKILLS
{", ".join(core_skills) if core_skills else "Communication, Basic Computer Knowledge, Problem Solving"}

CURRENTLY LEARNING
{", ".join(learning_skills) if learning_skills else "Career-relevant tools and technologies"}

PROJECTS
1. {career_name} Portfolio Project
   - Created a beginner-friendly project related to {career_name}.
   - Applied skills such as {", ".join(core_skills[:3]) if core_skills else "problem-solving and basic tools"}.

2. Skill Improvement Project
   - Practiced {", ".join(learning_skills[:3]) if learning_skills else "important career skills"}.
   - Built confidence through hands-on learning.

CERTIFICATIONS
Add your certifications or online courses here.

ACHIEVEMENTS
Add academic achievements, competitions, or participation details here.

DECLARATION
I hereby declare that the information provided above is true to the best of my knowledge.
"""

        cover_letter = f"""
Dear Hiring Manager,

I am writing to apply for an entry-level opportunity as a {career_name}.

I have an educational background in {education} and skills in {", ".join(core_skills[:5]) if core_skills else "relevant beginner skills"}. I am eager to learn, contribute, and grow professionally in this field.

I am currently improving my knowledge of {", ".join(learning_skills[:3]) if learning_skills else "career-relevant tools"} and building practical projects to strengthen my portfolio.

Thank you for considering my application.

Sincerely,
{name}
"""

    elif template == "restart":
        resume = f"""
{name}
{email} | {phone} | {location}

{note}

CAREER RESTART SUMMARY
Motivated candidate restarting or strengthening her career journey with interest in {career_name}.
Focused on learning, practical projects, and flexible career opportunities.

TARGET ROLE
{career_name}

CAREER STAGE
{career_stage}

EDUCATION
{education}
Add your college/university name here
Add passing year here

CURRENT SKILLS
{", ".join(core_skills) if core_skills else skills_text or "Add your skills here"}

TRANSFERABLE SKILLS
Communication, Responsibility, Time Management, Adaptability, Problem Solving

CURRENTLY LEARNING
{", ".join(learning_skills) if learning_skills else "Career-relevant skills"}

PROJECTS / PRACTICAL WORK
1. {career_name} Practice Project
   - Built to understand practical tasks related to {career_name}.

2. Career Restart Skill Project
   - Focused on improving missing skills and confidence.

PREFERRED WORK MODE
{preferred_work_mode}

CAREER GOAL
To build a stable and flexible career in {career_name} through continuous learning and beginner-friendly opportunities.
"""

        cover_letter = f"""
Dear Hiring Manager,

I am interested in applying for the {career_name} role.

I am currently restarting and strengthening my career journey with a focus on practical learning and skill development. My background includes {education}, along with skills such as {", ".join(core_skills[:5]) if core_skills else skills_text}.

I am responsible, adaptable, and committed to growing professionally. I would appreciate the opportunity to contribute to your organization.

Sincerely,
{name}
"""

    else:
        resume = f"""
{name}
{email} | {phone} | {location}

{note}

TARGET ROLE
{career_name}

PROFESSIONAL SUMMARY
Aspiring {career_name} with a background in {education}.
Skilled in {", ".join(core_skills[:5]) if core_skills else "relevant foundational skills"} and interested in {interests}.
Focused on building practical experience, improving industry-relevant skills, and becoming job-ready.

EDUCATION
{education}
Add your college/university name here
Add passing year here

CORE SKILLS
{", ".join(core_skills) if core_skills else skills_text or "Add your skills here"}

TOOLS / LEARNING AREAS
{", ".join(learning_skills) if learning_skills else "Career-specific tools and technologies"}

PROJECTS
1. {career_name} Portfolio Project
   - Designed a project related to {career_name}.
   - Applied skills such as {", ".join(core_skills[:3]) if core_skills else "basic tools and problem-solving"}.

2. Skill Gap Improvement Project
   - Created to improve knowledge of {", ".join(learning_skills[:3]) if learning_skills else "important missing skills"}.

3. Practical Career Project
   - Practiced real-world tasks related to {category}.

CERTIFICATIONS
Add relevant certifications or online courses here.

RELEVANT KEYWORDS
{career_name}, {category}, {", ".join(required[:8]) if required else ", ".join(core_skills[:8])}
"""

        cover_letter = f"""
Dear Hiring Manager,

I am writing to express my interest in the {career_name} role.

My educational background in {education}, along with my skills in {", ".join(core_skills[:5]) if core_skills else skills_text}, makes me interested in starting and growing in this field.

I am actively improving my knowledge of {", ".join(learning_skills[:3]) if learning_skills else "career-relevant areas"} and building projects to strengthen my practical understanding.

Thank you for considering my application.

Sincerely,
{name}
"""

    return jsonify({
        "resume": resume.strip(),
        "cover_letter": cover_letter.strip()
    })
    
@app.route("/chat", methods=["POST"])
def chat():
    data = request.get_json() or {}

    user_message = data.get("message", "")
    career_name = data.get("career_name", "")
    user_profile = data.get("user_profile", {})

    if not user_message:
        return jsonify({"reply": "Please ask something."})

    hf_api_key = os.getenv("HF_API_KEY")

    def fallback(reason="offline"):
        return f"""
⚠️ AI unavailable ({reason})

For {career_name or "this career"}:

• Learn required skills step-by-step  
• Practice small projects  
• Build portfolio  
• Apply for beginner jobs  

Your skills: {user_profile.get("skills", "")}
"""

    if not hf_api_key:
        return jsonify({"reply": fallback("no API key")})

    try:
        response = requests.post(
            "https://api-inference.huggingface.co/models/google/flan-t5-large",
            headers={
                "Authorization": f"Bearer {hf_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "inputs": f"""
You are a helpful AI assistant.

User Profile:
Skills: {user_profile.get("skills","")}
Education: {user_profile.get("education","")}

Career Context: {career_name}

Question: {user_message}

Answer clearly in bullet points:
"""
            },
            timeout=30
        )

        print("HF status:", response.status_code)

        try:
            result = response.json()
        except:
            print("Invalid JSON:", response.text)
            return jsonify({"reply": fallback("invalid response")})

        print("HF result:", result)

        if response.status_code != 200:
            return jsonify({"reply": fallback("API error")})

        reply = ""

        # ✅ SAFE parsing
        if isinstance(result, list) and len(result) > 0:
            reply = result[0].get("generated_text", "")

        elif isinstance(result, dict):
            reply = result.get("generated_text", "")

        if not reply:
            return jsonify({"reply": fallback("empty response")})

        return jsonify({"reply": reply.strip()})

    except Exception as e:
        print("HF error:", e)
        return jsonify({"reply": fallback("connection error")})
    
if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)